<a href="https://colab.research.google.com/github/yeonhas/TIL-2023-03/blob/main/Ai_ch3_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 10
b = 20
print(a+b)

30


파이썬 기초
실행 ctrl + enter

numpy : 수식 계산 ㅡ libary : 행렬처리

In [ ]:
import numpy as np
np.cos(3.141592)

print(np.round(0, 5),3)

0 3


### 파이썬 기초 : 비교, 반복

In [ ]:
import numpy as np
a = np.sin(1.7)
if a>0:
  print("sin값은 양수입니다")
else:
  print("sin값은 음수입니다") 

sin값은 양수입니다


In [ ]:
cnt = 1
while cnt < 11:
  print(cnt)
  cnt = cnt + 1

1
2
3
4
5
6
7
8
9
10


In [ ]:
for x in range(1,11):
  print(x)

1
2
3
4
5
6
7
8
9
10


### 파이썬 기초 : 리스트, 튜플, 딕셔너리, 집합


---


* 리스트(list) : 여러 개의 데이터 공간이 이어져 있는 데이터 타입으로 대괄호로 생성


In [ ]:
vs = [1,3,'Hi', 8.5]
print(vs)
print(vs[2])
vs[1]=5
print(vs[0:2])

print(vs[0:4])
print(vs[0:3])
print(vs[4:6])

[1, 3, 'Hi', 8.5]
Hi
[1, 5]
[1, 5, 'Hi', 8.5]
[1, 5, 'Hi']
[]


In [ ]:
vt=[]
vt.append(1)
vt.append(3)
vt.append('Hi')
print(vt)

[1, 3, 'Hi']




---


* 튜플(tuple) : 리스트와 유사하나 한번 만들면 수정할 수 없으며, 소괄호로 생성

In [ ]:
vp = (3, 4, 'sup')
print(vp)

# vp(1)=5 : 튜플은 수정이 불가능하다

(3, 4, 'sup')


### 파이썬 기초 : 리스트, 튜플, 딕셔너리, 집합


---
* 딕셔너리(dictionary) : 
 * key와 value를 쌍으로 가지는 데이터 타입
 * 연관 배열(associative arry)또는 해시(hash)
 * 순서가 없고 key를 검색하여 value를 얻으며, 중괄호로 생성


In [ ]:
vd = {'Title' : 'Marvel Comics', 'Year' : 1950, 'Country' : 'USA', 5: 'uptown'}
print(vd)
vd['price']=5000
print(vd)
print(vd['Title'])

{'Title': 'Marvel Comics', 'Year': 1950, 'Country': 'USA', 5: 'uptown'}
{'Title': 'Marvel Comics', 'Year': 1950, 'Country': 'USA', 5: 'uptown', 'price': 5000}
Marvel Comics




---


* 집합(set) : 리스트, 딕셔너리와 유사하나 항목에 순서와 이름(key)이 없음

In [ ]:
ve = {3,5,4}
print(ve)
ve.add(8)
print(ve)

{3, 4, 5}
{8, 3, 4, 5}


### 파이썬 기초 : numpy

* 복잡한 배열의 연산에 사용하는 library

In [ ]:
import numpy as np
n = np.array([[3,4,1,2],[8,2,4,9]])
print(n)
print(n.shape)

[[3 4 1 2]
 [8 2 4 9]]
(2, 4)


In [ ]:
# zeros() 함수는 0으로 된 배열, ones() 함수는 1로 된 배열을 생성
ne = np.zeros((3,5))
ns = np.ones((3,5,2))

In [ ]:
# expend_dims : 차원을 추가
n = np.expand_dims(n, 0) # 0번 차원을 추가
n = np.expand_dims(n,-1) # n이 1차원 배열인 경우, 두 번째 차원 축(즉 1번 차원)을 추가 (가장 마지막 차원보다 하나 더 상위 차원 추가)

In [ ]:
# reshape : 배열의 모양을 변경
n = np.array([[3,4,1,2],[8,2,4,9]])
m = np.reshape(n, (4,2))
print(n)
print(m)

[[3 4 1 2]
 [8 2 4 9]]
[[3 4]
 [1 2]
 [8 2]
 [4 9]]


### 파이썬 기초 : numpy 및 사용자 함수
* 다양한 함수들이 정의되어 있음
 * max : 최댓값, min : 최솟값, mean : 평균, std : 표준편차, sum : 합계

In [ ]:
n = np.array([[3,4,1,2],[8,2,4,9]])
mv = np.max(n)
print(mv)

a = np.min(n)
b = np.mean(n)
c = np.std(n)
d = np.sum(n)

print(a)
print(b)
print(c)
print(d)

9
1
4.125
2.7128168017763383
33


In [ ]:
# argmax : 최댓값의 인덱스, argmin : 최솟값의 인덱스
n = np.array([[3,4,1,2],[8,2,4,9]])
mv = np.argmax(n)
mx = np.argmin(n)
print(mv)
print(mx)

7
2


In [ ]:
# random : 임의의 수
rd = np.random.rand()
rc = np.random.rand(5,4)
print(rc)

[[0.06597855 0.19406294 0.62717172 0.28783925]
 [0.59944942 0.8319608  0.05233632 0.09681336]
 [0.54353225 0.35426378 0.78352741 0.49617335]
 [0.37061734 0.07424452 0.18989519 0.69629135]
 [0.54552464 0.2740142  0.71447563 0.77510801]]


In [ ]:
# 사용자 정의 함수를 만들 때는 def 사용
def add(v1, v2):
  sum = v1 + v2
  return sum

v = add(3,6)
print(v) 

9
